version: "3.8"
services:
  db:
    image: postgres:16
    container_name: postgres_lsbp
    environment:
      - .env
    ports:
      - "15432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: